# Generated by Django 6.0 on 2026-01-01 17:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chaiVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='chais/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('black', 'Black Tea'), ('green', 'Green Tea'), ('herbal', 'Herbal Tea'), ('oolong', 'Oolong Tea'), ('white', 'White Tea'), ('pu-erh', 'Pu-erh Tea')], max_length=200)),
            ],
        ),
    ]
