# Generated by Django 6.0 on 2026-01-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivariety',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='chaivariety',
            name='prices',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=6),
        ),
    ]
