# Generated by Django 6.0.1 on 2026-01-14 19:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performer', '0005_about_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_description',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='about_description',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='about_description',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
