# Generated by Django 6.0.1 on 2026-01-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performer', '0006_alter_about_description_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_description',
            name='subtitle',
            field=models.CharField(default='', max_length=300),
        ),
    ]
