# Generated by Django 6.0.1 on 2026-01-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performer', '0007_about_description_subtitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chaireview',
            old_name='date_created',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='chaireview',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
