# Generated by Django 6.0.1 on 2026-01-15 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performer', '0008_rename_date_created_chaireview_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaivariety',
            name='type',
            field=models.CharField(choices=[('black', 'Black Tea'), ('green', 'Green Tea'), ('herbal', 'Herbal Tea'), ('oolong', 'Oolong Tea'), ('white', 'White Tea'), ('pu-erh', 'Pu-erh Tea'), ('rose', 'Rose Tea'), ('ginger', 'Ginger Tea')], max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='chaireview',
            unique_together={('chai', 'user')},
        ),
    ]
