# Generated by Django 6.0.1 on 2026-01-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performer', '0009_alter_chaivariety_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaireview',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)]),
        ),
    ]
